### ISSUE TITLE
Dashboard view page has scrollbars 

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-dashboards#1011]
**Description:**
Default Dashboard view page has scrollbars 

![image](https://user-images.githubusercontent.com/20179540/44029770-1af8bfe6-9f1c-11e8-9033-46774e857d9b.png)

**Suggested Labels:**
Bug, 

**Suggested Assignees:**
@lasanthaS 

**Affected Product Version:**
4.3.M5

**OS, DB, other environment details and versions:**    
Windows, Chrome

**Steps to reproduce:**
View any pre shiped dashboard

**Comment by this** [comment]
Fixed with #1015
