### ISSUE TITLE
Screenshots and gifs need to be updated in "Viewing Dashboard" page

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-dashboards#1074]
**Description:**
In the page [1] screenshots and gifs are of SP 4.2.0. For example we have changed the theme change button to a light bulb instead of the toggle button.

Therefore we need to update the screenshots and details accordingly.

[1] https://docs.wso2.com/display/SP430/Viewing+Dashboards

**Affected Product Version:**
SP 4.3.0

**Comment by RukshiW** [comment]
Updated [1] with new images, gifs and related text to address the UI changes.
