### ISSUE TITLE
[Dashboard] Cannot delete generated widgets

### ISSUE THREAD

**Issue by lasanthaS** [wso2/carbon-dashboards#1079]
**Description:**
In the current implementation, once a widget is generated via the 'Widget generation wizard' it is getting stored in the underlying database. But there is no functionality to delete these widgets once they are added.

This can be a problem if the user has added the widget mistakenly.

**Affected Product Version:**
WSO2SP 4.3.0

**Comment by TanyaM** [comment]
We have an existing api to delete a generated widget from the database but this api has a bug at [1] as we pass widget type as CUSTOM.

[1] https://github.com/wso2/carbon-dashboards/blob/master/components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/WidgetMetadataProviderImpl.java#L100

**Comment by Niveathika92** [comment]
This is introduced from SP-4.4.0-M14
