### ISSUE TITLE
Design/Settings button are not working in firefox

### ISSUE THREAD

**Issue by NisalaNiroshana** [wso2/carbon-dashboards#1087]
**Description:**
In the dashboard listing page, Design and settings button are not working when we use firefox browser

**Suggested Labels:**
@Bug

**Suggested Assignees:**
@TanyaM @lasanthaS @this 

**Affected Product Version:**
SP-4.2.0

**OS, DB, other environment details and versions:**    
Firefox browser

**Steps to reproduce:**
Go to dashboard listing page of portal using Firefox browser

**Comment by this** [comment]
Is this same as https://github.com/wso2/product-sp/issues/712, if so we have fixed it and fix is available in SP-4.3.0.

**Comment by this** [comment]
Closing as duplicate of https://github.com/wso2/product-sp/issues/712
