### ISSUE TITLE
CEP - getDatasources

### ISSUE THREAD

**Issue by aylesm** [wso2/carbon-dashboards#171]
I'm trying to create a new gadget in the dashboard 'create a gadget' feature.  I've configured a datasource in CEP and am getting an error message back "No datasources available to create a gadget. Please create a datasource to proceed.".  Looking at rt.jag it looks as though you are searching for eventPublishers that are of type ui.  This doesn't look right to me.  Please help.

**Comment by sinthuja** [comment]
Hi Aylesm,

We have revamped the gadget generation tool to be more pluggable and CEP (Real time Data source) is yet another datasource that is available OOB. Anyhow regarding your question about creating the event publisher, basically you need to create an UI event publisher to make connection from the stream to UI (stream is the first class concept in the stream only having stream you can't communicate to external applications, for that you need to create the event publisher), and then created gadgets can listed to the events that arrive in that wire and display the data. Underneath we are using web sockets for this. 

Please try out gadget generation tool in the latest pack, provide your feedback.
