### ISSUE TITLE
Modify the dashboard.json to place widgets inside blocks

### ISSUE THREAD

**Issue by lasanthaS** [wso2/carbon-dashboards#492]
Currently `dashboard.json` maps widgets with each block using the block ID as follows.

```
{
  ...
  "blocks": [
    {
      "id": "3f64fcc44bafcd84a593072c6c9bdbd603",
      "x": 0,
      "y": 0,
      "width": 6,
      "height": 4
    },
    ...
  ],
  "widgets": {
    "3f64fcc44bafcd84a593072c6c9bdbd603": {
        ...
    },
    ...
  },
  ...
}
```
Instead it is better and cleaner if we can remove this mapping and place the widget descriptor within the block itself as follows.

```
{
  ...
  "blocks": [
    "3f64fcc44bafcd84a593072c6c9bdbd603": {
      "x": 0,
      "y": 0,
      "width": 6,
      "height": 4,
      "widget": {
        ...
      }
    },
    ...
  ],
  ...
}
```

**Comment by udarakr** [comment]
Let's use the containeID as the key for the block as mentioned in above sample. Right now we have a auto increment index.

**Comment by NisalaNiroshana** [comment]
Since there is no further development in UUF based dashboard, close the issue by labeling it to UUF-DS
