### ISSUE TITLE
Create a common UUF component to host artifacts to both designer and view

### ISSUE THREAD

**Issue by udarakr** [wso2/carbon-dashboards#512]
Eg:- 
- publishToTopics function can be exposed via portal.dashboards.functions.common global object rather exposing via portal.dashboards.functions.view and portal.dashboards.functions.designer
- Expose apis via this component

**Comment by NisalaNiroshana** [comment]
Since there is no further development in UUF based dashboard, close the issue by labeling it to UUF-DS
