### ISSUE TITLE
[Designer] Save button in designer will only save the current page

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-dashboards#636]
**Description:**
Save button in dashboard designer is expected to save the entire dashboard. But currently it only saves the current page.

**Affected Product Version:**
4.0.0.m15

**Steps to reproduce:**
1. Create a  dashboard and add few widgets to the home page
2. Add another page to the dashboard without clicking the "Save" button
3. Add new widgets to the second page
4. Click "Save" button to save the dashboard

Observation : Only second page will be saved and widgets added for the home page will not be saved.

**Comment by NisalaNiroshana** [comment]
Fixed with https://github.com/wso2/carbon-dashboards/pull/903. Now there is no save button. the dashboard will be saved automatically.
