### ISSUE TITLE
Changing landing page in designer mode is buggy

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-dashboards#637]
**Description:**
If we change the landing page to a different page other than the home, it is not possible to change it back to Home page.

**Affected Product Version:**
4.0.0.m15

**Steps to reproduce:**
1. Create a dashboard with two pages
2. Mark the second page as Landing page
3. Try to change the landing page to the home page again

Observation : "Mark as Home Page" option is disabled

**Comment by NisalaNiroshana** [comment]
Resolved with https://github.com/wso2/carbon-dashboards/pull/672
