### ISSUE TITLE
Test dashboard runtime for mysql

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-dashboards#736]
**Description:**
Dashboard runtime needs to be tested for mysql database. This needs to use both dashboard resource database and permission database in mysql

**Affected Product Version:**
4.0.0.beta2

**Comment by lasanthaS** [comment]
Tested for multiple database types with following PRs.
* Dashboards: https://github.com/wso2/carbon-dashboards/pull/783
* Permissions: https://github.com/wso2/carbon-analytics-common/pull/497

Hence closing issue as solved.
