### ISSUE TITLE
Revenue percentage widget is not displayed properly in Portal.

### ISSUE THREAD

**Issue by ChathurikaA** [wso2/carbon-dashboards#745]
**Description:**
Revenue percentage widget is not displayed properly. It only showed the upper part of a widget since it shows a large view of it.

**Suggested Labels:**
Improvement

**Suggested Assignees:**
@lasanthaS 

**Affected Product Version:**
wso2sp-4.0.0-beta3

**OS, DB, other environment details and versions:**    
OS: 16.04.1-Ubuntu
Web Browser: Chrome: Version 58.0.3029.110, 

**Steps to reproduce:**
1.Create new dashboard called Sales Statistics. 
2.Create a new page called Sales-stats-test.
3.Drag and drop revenue percentage widget.
The widget is displayed in large size. The upper part of the widget is displayed
Also got to view and check the page. In there also it is not displayed properly.

![notfullview](https://user-images.githubusercontent.com/24618493/33872885-c210882a-df3e-11e7-89d6-2eb6a0940484.png)

**Comment by suganyasuven** [comment]
This issue is in revenue by region widget as well. 
![screenshot from 2017-12-13 14-24-09](https://user-images.githubusercontent.com/30232477/33931098-08d36490-e015-11e7-8e9c-7c6f06afbb08.png)
