### ISSUE TITLE
Designer of a dashboard is served in the designer context 

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-dashboards#748]
**Description:**
Designer component of a dashboard should only be served through the portal app context. But it is also served in the designer context.

**Affected Product Version:**
4.0.0.beta3 

**Steps to reproduce:**
1. Go to the dashboard listing page and click on settings button in a desired dashboard
2. Click cancel in the Settings page.
3. Click on the Design button of the dashboard card 

Designer will be served in designer context instead of portal
Ex : https://<IP>:9643/designer/systemanalytics

Same is observed for Viewer as well.

**Comment by lasanthaS** [comment]
The flow which this issue occurs has been resolved with the issue https://github.com/wso2/carbon-dashboards/issues/747. Hence closing.
