### ISSUE TITLE
There is no "Home" button to redirect to the home-page of the dashboard.

### ISSUE THREAD

**Issue by ChathurikaA** [wso2/carbon-dashboards#752]
**Description:**
There is only 'BACK' and 'SAVE' button is displayed. There is no HOME button to redirect to the home page of the portal.

**Suggested Labels:**
improvement.

**Suggested Assignees:**
@lasanthaS 

**Affected Product Version:**

wso2sp-4.0.0-beta3

**OS, DB, other environment details and versions:**
OS: 16.04.1-Ubuntu
web browswer: firefox - 57.0.1, chrome - 58.0.3029.110    

**Steps to reproduce:**
1.Create new dashboard called Sales Statistics.
2. Go to design option.
It only displays 'BACK' and 'SAVE' options on the displayed web page.  

**Suggestion:**
It is better to have a 'HOME' button to redirect to the portal home page. If not it is confusing how to go back to the home-page of the portal. We have to press BACK button many times or to use the back icon in the browser to reach the portal home page again.

**Comment by lasanthaS** [comment]
In the Designer **Back** button serves the same purpose as **Home**. Hence there is no need of introducing a new button there. In order to eliminate the confusion +1 to proceed with renaming the Back button to **Home**.

**Comment by ChathurikaA** [comment]
This is not a bug since only back button direct to the home-page.
