### ISSUE TITLE
Title 'Create dashboard' should be change to 'Create Dashboard'.

### ISSUE THREAD

**Issue by ChathurikaA** [wso2/carbon-dashboards#757]
**Description:**
It is good to change the 'Create dashboard' title to 'Create DashBoard'. 
![createdb](https://user-images.githubusercontent.com/24618493/33883106-8361a574-df60-11e7-968e-48b262e8bc2a.png)

**Suggested Labels:**
Type/bug, Severity/Trivial

**Suggested Assignees:**
@lasanthaS, @edgars 

**Affected Product Version:**
dashborad version: v4.0.0.beta4
productSP: wso2sp-4.0.0-beta3

**OS, DB, other environment details and versions:**    
OS: 16.04.1-Ubuntu.
web browswer: firefox - 57.0.1, chrome - 58.0.3029.110

**Steps to reproduce:**
1.Go to <PRODUCT_HOME>/bin/ and Start the dashboard using ./dashboard.sh command in console.
4. Open the Dashboard in a web browser. (localhost:9643/portal/)
5. Log in to the dashboard using default username and password. 
6. Click CREATE DASHBOARD option.

**Comment by lasanthaS** [comment]
This needs to be changed to **Create Dashboard**
