### ISSUE TITLE
[Designer] When clicking on a page, previously opened page accordion does not collapse in the 'PAGES' panel

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-dashboards#759]
**Description:**
In dashboard designer, when we click a page to edit, previous edited page is  remains opened.
**Suggested Labels:**
UI/UX improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-beta3
Dashboard Version - v4.0.0.beta4

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Steps to reproduce:**
Create some pages in a dashboard.
Then edit one page. 
Then click another page to edit, the prevoius edited page remains collapsed. 
![screenshot from 2017-12-12 17-44-08](https://user-images.githubusercontent.com/30232477/33884589-4e934bd0-df66-11e7-963a-1004bf2de2d1.png)

**Comment by lasanthaS** [comment]
In order to make the flow smoother, it is better to collapse all the page info cards except the current one.

**Comment by NisalaNiroshana** [comment]
Fixed with https://github.com/wso2/carbon-dashboards/pull/903
