### ISSUE TITLE
In Dashboard Designer, UX improvement is needed.

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-dashboards#761]
**Description:**
In Dashboard designer,  when we click to edit another page without saving previous edited page, the modifications we have done for the previous page is being lost. So it should confirm whether modifications should be saved  or not.
**Suggested Labels:**
Improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-beta3
Dashboard Version - v4.0.0.beta4

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Steps to reproduce:**
Create some pages in a dashboard.
Then edit one page.
Then click another page to edit without saving that page.
Then go to the previous edited page, the modifications you have done is lost.

**Comment by lasanthaS** [comment]
Closing this issue since https://github.com/wso2/carbon-dashboards/issues/636 reports the same issue.
