### ISSUE TITLE
[Designer] Widget Configuration panel does not have a close button

### ISSUE THREAD

**Issue by ChathurikaA** [wso2/carbon-dashboards#762]
**Description:**
To close the widget configuration bar, we have to click again widget configuration icon which is not much user-friendly. Therefore, it is better to add a close icon to the widget configuration.

![congig](https://user-images.githubusercontent.com/24618493/33886586-12afe11c-df6d-11e7-825a-01a33c8656fe.png)

**Suggested Labels:**
Type/improvement, Severity/minor 

**Suggested Assignees:**
@lasanthaS , @edgars  

**Affected Product Version:**
dashborad version: v4.0.0.beta4
productSP: wso2sp-4.0.0-beta3
web browswer: firefox - 57.0.1, chrome - 58.0.3029.110

**OS, DB, other environment details and versions:**    
OS: 16.04.1-Ubuntu.
web browswer: firefox - 57.0.1, chrome - 58.0.3029.110
    
**Steps to reproduce:**
Create new dashboard called Sales Statistics.
Create a new page called Sales-stats-test.
Drag and drop revenue percentage widget.
Then click the icon "widget configuration" on the page.

**Comment by NisalaNiroshana** [comment]
Fixed with https://github.com/wso2/carbon-dashboards/pull/903
