### ISSUE TITLE
Shipping samples with the products doesn't add much value as those are minified

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-dashboards#763]
**Description:**
There are several sample widgets that is shipped with the product (Ex : WidgetState, Publisher, Subscriber etc). But in the product binary these widgets are transcompiled, built and minified. 

So it will not add any value as a sample as a user cannot view the actual source of the widget.

**Comment by lasanthaS** [comment]
There are 2 options we can consider to solve this issue.
1. Keep the sample widgets as it is, but provide links to "Widget guide" in product documentation and samples' source code in GitHub within the UI of the widget (as information bar?).
2. Ship the sample widgets within pack through samples directory (with source code and scripts to deploy them).

WDYT?

**Comment by TanyaM** [comment]
+1 for option 1

**Comment by TanyaM** [comment]
Added information in the SP docs
