### ISSUE TITLE
Current designing/editing page should be highlighted in the 'PAGES' panel

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-dashboards#764]
**Description:**
In DashBoard designer, the current page is not highlighted. It is not user friendly as current page can be identified through address only.
![screenshot from 2017-12-13 09-51-29](https://user-images.githubusercontent.com/30232477/33921687-74e5a6cc-dfeb-11e7-9225-109487bcefa7.png)

**Suggested Labels:**
Improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-beta3
Dashboard Version - v4.0.0.beta4

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Comment by this** [comment]
Fixed by https://github.com/wso2/carbon-dashboards/pull/903
