### ISSUE TITLE
In dashboard designer, Widgets should be ordered in a proper way.

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-dashboards#773]
**Description:**
In dashboard designer, Widget order keeps changing when we refresh the dashboard designer every time. So it is better to arrange it in a defined order.
![screenshot from 2017-12-13 16-08-40](https://user-images.githubusercontent.com/30232477/33935008-7958b9bc-e020-11e7-84d2-bb52440e4a86.png)
![screenshot from 2017-12-13 16-10-29](https://user-images.githubusercontent.com/30232477/33935015-7d65d2f6-e020-11e7-8b45-7aad3b7979bd.png)

**Suggested Labels:**
Improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-beta3
Dashboard Version - v4.0.0.beta4

**OS, DB, other environment details and versions:**    
OS: 16.04.1-Ubuntu

**Comment by TanyaM** [comment]
Could you please define what you meant by "Proper way" ? If its ordering them in alphabetical order by their name  IMO there is no added advantage as the Widget listing has a search option where you can search a desired widget.

**Comment by suganyasuven** [comment]
In dashboard designer, Widget order keeps changing when we refresh the dashboard designer every time. So it would be better to arrange it in a defined order.
I have improved the title and description.
