### ISSUE TITLE
In Dashboard viewer, it is better to have that toggle switch for dark and light at the top of the left pane and add tool tip as well.

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-dashboards#779]
**Description:**
In Dashboard viewer, it is better to have that toggle switch for dark and light at the top of the left pane and add tool tip as well. 

**Suggested Labels:**
Improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-beta3
Dashboard Version - v4.0.0.beta4

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Steps to reproduce:**
Create some pages in a dashboard. 
Then if you want to switch from dark to light, you have to go down. It is not much user-friendly.

**Comment by lasanthaS** [comment]
The logo and the dashboard name should be more prominent and prioritize there in the dashboard view sidebar instead of the theme toggle button. Hence -1 for moving the toggle button to top of the page. 

But +1 for adding a tooltip there since there is no label saying what the toggle button does.
