### ISSUE TITLE
Console warning is displayed when accessing a dashboard

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-dashboards#798]
**Description:**
Below warning can be observed in the browser console when accessing a dashboard.

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

**Affected Product Version:**
4.0.0

**Steps to reproduce:**
1. Log in to the portal and open the browser console
2. Click on Design button of a desired dashboard

Following warning can be observed in the browser console.

**Comment by CharukaK** [comment]
This problem arises with the introduction of passive event listeners for [chrome v51](https://developers.google.com/web/updates/2016/06/passive-event-listeners),
From my findings on the problem, this arises as a result of using jQuery event-handlers in golden-layout layout manager. As of now the current released version of jQuery(v3.21)  doesn't have support for passive event listeners they have stated that they will have support for passive-event listeners in [v4.0.0 of  jQuery](https://github.com/jquery/jquery/issues/3886#issuecomment-350880747) until this version gets released and updated in the layout manager this issue will remain to be so. the on-going discussion of adding passive event listeners can be found [here](https://github.com/jquery/jquery/issues/2871)
