### ISSUE TITLE
In Dashboard Designer, User info widget is not updating the user information

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-dashboards#826]
**Description:**
In Dashboard Designer, User info widget is not updating the user information

**Suggested Labels:**
Bug

**Affected Product Version:**
SP Version - wso2sp-4.0.0-RC1

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Steps to reproduce:**
1) Create new dashboard called Sales Statistics.
2) Create a new page called Server1-Statistics
3) Drag and drop User info widget. It is showing blank page and not updating the user info.
![screenshot from 2017-12-21 10-12-27](https://user-images.githubusercontent.com/30232477/34240905-9b449074-e637-11e7-8d58-83bf9fcd6275.png)

**Comment by this** [comment]
fixed with https://github.com/wso2/carbon-dashboards/pull/827
