### ISSUE TITLE
Creating a new page without saving the current page will display the widgets of the current page in the newly created page

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-dashboards#863]
**Description:**
 If we create a new page without saving the current page, widgets in the current page is displayed in the new page.

**Suggested Labels:**
UI/UX improvement

**Affected Product Version:**
wso2sp-4.1.0-RC1

**Steps to reproduce:**
1. Create a new dashboard.
2. Create a page and drag and drop a widget.
3. Without saving the current page, create a new page.
4. You can see, the widget that we dropped in the previous page, displayed in the new page.

**Comment by NisalaNiroshana** [comment]
This is fixed with the new designer implementation
