### ISSUE TITLE
Hamburger menu Button in dashboard is not working .

### ISSUE THREAD

**Issue by Meruja** [wso2/carbon-dashboards#864]
**Description:**
The hamburger menu button which should hide the right-panel in the dashboard view page does not work.

**Affected Product Version:**
- wso2sp-4.1.0-RC1
- carbon-dashboards v4.0.14

**Steps to reproduce:**
1.Log in to the dashboard(portal).
2. Click on the `View` button of an existing dashboard (e.g. Sales Dashboard)
3.Click on the hamburger menu button

**Comment by this** [comment]
@NisalaNiroshana, @lasanthaS Any thoughts on this?
