### ISSUE TITLE
User menu does not indicates that its purpose properly

### ISSUE THREAD

**Issue by this** [wso2/carbon-dashboards#879]
**Description:**
Current user menu (see below screenshot) doesn't appears a an "User" menu.
![image](https://user-images.githubusercontent.com/11549922/39031828-3cfdcbca-4488-11e8-8a82-2dbb0bb84084.png)
- Instead of the kebab menu, it should have the user icon to indicates that its an menu that contains operations for the current logged-in user.
![image](https://user-images.githubusercontent.com/11549922/39032134-d5c504e4-4489-11e8-9164-bbaa6ff99ab9.png)
- Menu should be highlighted on mouse hover.

**Affected Product Version:**
sp-4.1.0

**Comment by NisalaNiroshana** [comment]
Fixed with #896
