### ISSUE TITLE
Cannot change language in the portal app

### ISSUE THREAD

**Issue by this** [wso2/carbon-dashboards#882]
**Description:**
Cannot change language or add a new language as locale `en` is [hard-coded](https://github.com/wso2/carbon-dashboards/blob/v4.0.15/components/dashboards-web-component/src/App.jsx#L78).

**Affected Product Version:**
sp-4.1.0

**Comment by this** [comment]
To fix this, some improvements has to be done in `carbon-ui-server` as well. See https://github.com/wso2/carbon-ui-server/issues/73.

**Comment by TanyaM** [comment]
@this : Could you please point where en is hardcoded? 
Language can be changed in portal app by putting a new locale file into SP_HOME/wso2/dashboard/deployment/web-ui-apps/portal/public/locales
