### ISSUE TITLE
Dashboard and Widgets table creation failed in Mysql 

### ISSUE THREAD

**Issue by ksdperera** [wso2/carbon-dashboards#884]
**Description:**
The Dashboard and Widgets table create query failed in MySql. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by this** [comment]
@ksdperera Does PR #885 fully fixes this issue?

**Comment by ksdperera** [comment]
Yes, it does. Please track the issue https://github.com/wso2/product-sp/issues/548 where these template queries are not copied into the SP distribution.

**Comment by this** [comment]
Fixed by #885
