### ISSUE TITLE
Table Chart Type is not scrollable

### ISSUE THREAD

**Issue by kts-desilva** [wso2/carbon-dashboards#995]
**Description:**
A table with a large number of rows is not scrollable. Hence the table content is not accessible.

**Steps to reproduce:**
Create a widget with a table chart type with a large dataset.

Tested with a table of 120 records and only 30 are visible in the dashboard.
No scrolling option to view the rest of the data.

**Comment by ThisaruGuruge** [comment]
Have you tried using `ScrollBars` component?

**Comment by erangatl** [comment]
Tables should ideally use pagination.

**Comment by TanyaM** [comment]
Closing since tables can use pagination
