### ISSUE TITLE
Widget generation wizard backend does not publish when there is no data

### ISSUE THREAD

**Issue by NisalaNiroshana** [wso2/carbon-dashboards#996]
**Description:**
Currently, Widget generation wizard backend does not publish when there is no data. But we need to publish an empty data set even there are no data. then users can identify it and change the charts and etc based on the empty response.

**Suggested Labels:**
@bug

**Suggested Assignees:**
@lasanthaS 

**Affected Product Version:**
SP 4.2.0

**OS, DB, other environment details and versions:**    
ALL

**Related Issues:**
NA

**Comment by TanyaM** [comment]
Fixed with https://github.com/wso2/carbon-analytics/pull/1401 in carbon-analytics repo.
